//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBM.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARArtist
    {
        public int ID_Artist { get; set; }
        public int ID_AR { get; set; }
    
        public virtual AR AR { get; set; }
        public virtual AR AR1 { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
