//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBM.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveA
    {
        public int ID_ArchiveA { get; set; }
        public string Login { get; set; }
        public string Band_or_Artist_Name { get; set; }
        public byte[] Photo { get; set; }
        public int Telephone_Number { get; set; }
        public string Password { get; set; }
        public int IDArtist { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
