//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBM.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveAR
    {
        public int ID_ArchiveAR { get; set; }
        public string Login { get; set; }
        public string FLO { get; set; }
        public int Telephone_Number { get; set; }
        public string Password { get; set; }
        public int IDAR { get; set; }
    
        public virtual AR AR { get; set; }
    }
}
