//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBM.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveS
    {
        public int ID_ArchiveS { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string List { get; set; }
        public string Feat { get; set; }
        public string Describtion { get; set; }
        public System.TimeSpan Time { get; set; }
        public int IDSongs { get; set; }
        public int IDArtist { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Songs Songs { get; set; }
    }
}
